version: 0.1
phases:
  build:
    commands:
      - npm install
      - npm run webpack

  
artifacts:
  files:
    - index.html
    - favicon.io
    - styles/*
    - images/*
    - dist/bundle.js
    - js/*
    - js/projects/*
    - js/common/*
    - projects/*.html
    - blogs/*
    - projects/*